### PR TITLE
draft: https://github.com/napari/napari/issues/6350

### PR DESCRIPTION
**Pull request by VolkerH**
supporting material for https://github.com/napari/napari/issues/6350

No intention to leave draft or be reviewed.

### CODE REVIEW

**Comment by tlambert03** [comment]
I read https://github.com/napari/napari/issues/6350 ... but I still don't quite get this one.  It looks like you're prepping to be able to pin `pydantic >2` by removing the version check?  but i don't think that would be the goal of a napari update?

**Comment by VolkerH** [comment]
@jni asked me to put in what I had tried in terms of making napari work
with pydantic 2.4 as draft PRs. This was just part of a quick hack to test
napari with `pydantic.v1` imports everywhere. I hard-coded pyappkit to use
pydantic v2.4 just for this single (failed) test on my local machine. This
is in no way intended to be a feature suggestion.

**Comment by tlambert03** [comment]
> This is in no way intended to be a feature suggestion.

yep, I gathered that from the original message :) 
I guess I was more curious to hear why you had to do this at all to make app-model work with pydantic v2.4 ... since I would have expected app-model to already be all set (since #98)

**Comment by VolkerH** [comment]
Ah... I was just trying to make sure that app-model was also using
pydantic.v1.* rather than pydantic for consistency with the other packages
I patched. I had never looked at app_model before and wasn't sure whether
the compatibility layer would work otherwise. (if it is just local use
within it shouldn't matter of course, but I wasn't sure whether napari
somehow sends/receives pydantic classes from/to app_model machinery.

**Comment by tlambert03** [comment]
ah, gotcha.  thanks!

**Comment by jni** [comment]
Yeah, sorry for the noise, a lot of activity happening with limited communication. I think what we want to do with napari is to allow it to work with *either* v1 or v2. Then @VolkerH you'd be unstuck with your own work because you could install v2 for your library *and* use napari, within the same env. Correct?

**Pull request closed without merging**
